= Høringsnotat: Fotogrammetriske registreringsinstrukser versjon 2024-01-01
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2023-11-10

////
CAUTION: {publisert} 
////

== Høring 

=== Opplegg for oppdatering av FKB Fotogrammetriske registeringsinstrukser
I tråd med beskrivelsene i http://sosi.geonorge.no/Standarder/FKB_generell_del/#truerevisjon[FKB generell del] utføres revisjon av FKB produktspesifikasjoner og 
fotogrammetriske registreringsinstrukser maksimalt 1 gang pr. år og fortrinnsvis i forbindelse med nyttår slik at dokumentasjonen er klar til bruk for kommende kartleggingssesong.

Etter innføring av FKB 5.0 Fotogrammetriske registreringinstrukser har det blitt utarbeidet årlige _vedlegg til FKB Fotogrammetriske registreringsinstrukser_ som samler opp
avklaringer rundt spørsmål knyttet til instruksene i inneværende kartleggingssong. Se https://kartverket.no/metadata/FKB50/Vedlegg_Fotogrammetrisk_FKB_2023.html[eksempel for 2023 her]. 
Det er et mål at innholdet i disse vedleggene er minst mulig og at avklaringene som gjøres hvert år derfor innarbeides i de fotogrammetriske registreringsinstruksene før neste kartleggingssesong.
Revisjonen som er utført høsten 2023 er stort sett et forsøk på å innarbeide innholdet i årets vedlegg i registreringsinstruksene samt noen andre mindre presiseringer/justeringer.

=== Standardiseringsprosjekt FKB 5.1
I forbindelse med arbeidet med å ta i bruk FKB 5.0 produktspesifikasjonene i forvaltningen av FKB-data (Sentral FKB) er det oppdaget behov for noen tekniske justeringer. 
Dette gjelder konkret modellering av assosiasjoner og håndtering av kodeliste for kommunenummer. Det er derfor under oppstart et eget standardiseringsprosjekt for
å gjøre disse justeringene. Målet er å få til en rask framdrift slik at disse oppdateringene også kan bli sendt på høring før 1.jan 2024.

Justeringene i de fotogrammetriske registreringsinstruksene kommmer i forkant av dette standardiseringsarbeidet og det forutsettes derfor at endringene i FKB produktspesifikasjonene ikke berører innholdet i disse.
Versjonsnummeret til FKB Produktspesifikasjonene kan imidlertid bli oppdatert for en del datasett og vil da bli justert i endelige versjoner registreringsinstruksene. 

Ta kontakt med Nils Ivar Nes (nesnil@kartverket.no) dersom du ønsker å bidra i standardiseringsprosjektet.

=== Svar på høring
Høringssvar på oppdateringene i FKB Fotogrammetriske registreringsinstrukser v2024-01-01 sendes til Mika Sundin (sunmik@kartverket.no) *innen 1.desember 2023*.

Planen er å gjennomgå høringssvar og tilgjengeliggjøre endelige høringssvar før jul, dvs. innen 22.des 2023. 


== Høringsdokumenter

=== Generelt om høringsdokumentene

På grunn av høye krav til universell utforming av dokumentasjon som er svært arbeidskrevende å løse i PDF-formatetet legges det fra og med 
ny versjon av registreringsinstruksene opp til at dokumentasjonen kun tilgjengeliggjøres som HTML. De som ev. ønsker dokumenter på PDF/papir kan printe fra HTML.

Arbeidet med å utarbeide dokumentasjon fra FKB produktspesifikasjoner og registreringsinstrukser er nå flyttet ut i åpne repoer på github.com. 
Dette innebærer at asciidoc-filer, figurer og ferdige html-filer løpende er tilgjengelige på github.

I forbindelse med høringen vises det direkte til repoet på github og en visning av høringsversjonen av html-dokumentet vist gjennom tjenesten htmlpreview.github.io. 

Se endringslogg i de enkelte dokumentene for en oversikt over endringer. Alle høringsdokumentene er gitt publiseringsdato 2023-11-20.

=== Fotogrammetrisk registreringsinstruks FKB-Arealbruk v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_arealbruk

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_arealbruk/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-BygnAnlegg v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygnanlegg

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygnanlegg/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Bygning v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygning

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygning/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Ledning v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_ledning

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_ledning/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Naturinfo v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_naturinfo

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_naturinfo/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-TraktorvegSti v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_traktorvegsti

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_traktorvegsti/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Vann v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_vann

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_vann/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Veg v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_veg

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_veg/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks Elveg v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_elveg

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_elveg/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]




|===