= Høringsnotat Fotogrammetriske registreringsinstrukser 2024-01-01
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2023-11-10

////
CAUTION: {publisert} 
////

== Høring 

=== Opplegg for oppdatering av FKB Fotogrammetriske registeringsinstrukser
Litt om opplegget med årlig "vedlegg til" som innarbeides i registreringsinstrukser det påfølgende året. 

=== Standardiseringsprosjekt FKB 5.1
Henvise til standardiseringsprosjekt 5.1

=== Svar på høring
Høringsfrist og hvor/hvordan svar på høring skal sendes..

Plan for når endelige versjoner skal tilgjengeliggjøres.



== Høringsdokumenter

=== Generelt om høringsdokumentene

På grunn av høye krav til universell utforming av dokumentasjon som er svært arbeidskrevende og løse i PDF-formatetet legges det fra og med 
ny versjon av registreringsinstruksene opp til at dokumentasjonen kun tilgjengeliggjøres som HTML. 

Arbeidet med å utarbeide dokumentasjon fra FKB produktspesifikasjoner og registreringsinstrukser er nå flyttet ut i åpne repoer på github.com. 
Dette innebærer at asciidoc-filer, figurer og ferdige html-filer løpende er tilgjengelige på github.

I forbindelse med høringen vises det direkte til repoet på github og en visning av høringsversjonen av html-dokumentet vist gjennom tjenesten htmlpreview.github.io. 

=== Fotogrammetrisk registreringsinstruks FKB-BygnAnlegg v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygnanlegg
https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygnanlegg/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]


=== Fotogrammetrisk registreringsinstruks FKB-Bygning v2024-01-01

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygning
https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_byging/blob/master/registreringsinstruks/index.html[HTML-visning av dokument]





Linker til html-dokumenter på github

|===