= Vedlegg til FKB Fotogrammetriske registreringsinstrukser - versjon 5.0
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:URLrot: https://sosi.geonorge.no/registreringsinstrukser
:fkb: http://sosi.geonorge.no/Standarder/FKB_generell_del
:publisert: Oppdatert 2022-05-24

CAUTION: {publisert} 

== Vedlegg til FKB Fotogrammetriske registreringsinstrukser - versjon 5.0

=== Innledning

FKB Fotogrammetriske registreringsinstrukser - versjon 5.0 - ble tilgjengeliggjort i januar 2022 og lagt til grunn for FKB kartleggingsprosjekter gjennom Geovekst med datafangst i 2022. Disse dokumentene er grunnlaget for inngåtte avtaler og det er derfor lite hensiktsmessig å endre de fotogrammetriske registreringsinstruksene underveis i et pågående kartleggingsprosjekt.

I løpet av våren 2022 er det gjennomført et FKB 5.0 testprosjekt der kartleggingsfirmaene i Norge har levert inn data basert på de nye spesifikasjonene for et lite område. Basert på erfaringene fra dette prosjektet er det behov for å presisere tolkning/håndtering av de FKB 5.0 registreringsinstruksene på en del områder. Dette dokumentet samler disse presiseringene for hvert datasett og bør derfor leses sammen med de fotogrammetriske registreringsinstruksene ved gjennomføring av FKB kartleggingsprosjekter 2022.

Det vil være naturlig at justeringene/presiseringene som er beskrevet i dette dokumenten innarbeides i reviderte FKB registreringsinstrukser som vil bli benyttet i neste kartleggingssesong.

Linker:

* FKB 5.0 generell del: {fkb}
* Geovekst produktspesifikasjoner og registreringsinstrukser: https://kartverket.no/geodataarbeid/geovekst/fkb-produktspesifikasjoner



== FKB Fotogrammetriske registreringsinstrukser

:ds: Elveg
:spek: {URLrot}/{ds}/2.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 2.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:




:ds: FKB-Arealbruk
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Bane
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-BygnAnlegg
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Bygning
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Høydekurve
:spek: {URLrot}/{ds}/5.0/Punktsky_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Ledning
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Naturinfo
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-TraktorvegSti
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Vann
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:



:ds: FKB-Veg
:spek: {URLrot}/{ds}/5.0/Fotogrammetrisk_2022-01-01/.
=== {ds}

Fotogrammetrisk registreringsinstruks for {ds} 5.0 er tilgjengelig på {spek}

Følgende presiseringer/justeringer av spesifikasjonen:

