= Høringsnotat Punktsky og Elveg 
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:SOSITEST: https://skjema.geonorge.no/SOSITEST/produktspesifikasjon
:REGINST: https://skjema.geonorge.no/SOSITEST/registreringsinstruks
:publisert: Oppdatert 2021-11-19

CAUTION: {publisert} 

== Høring

I forbindelse med revisjon av FKB var alle FKB-produktspesifikasjonene på høring i oktober. I tillegg til produktspesifikasjonene var også de fotogrammetriske registreringsinstruksene ute på høring.

Parallelt med revisjon av FKB har det blitt gjennomført en revisjon av FKB-Laser, som i sin helhet erstattes med Produktspesifikasjon Punktsky 1.0. Punktsky 1.0 viderefører rammeverket for luftbåren topografisk LiDAR, men utvider med flere datafangstmetoder som bathymetri og bildematching. 

I tillegg til en ny Punktsky spesifikasjon har det blitt utarbeidet to registreringsinstrukser som legger punktsky data til grunn for vektorisering av tradisjonelle kartobjekter.

I 2018 ble det utgitt et utkast til en produktspesifikasjon for klassifisering og vektorisering av ledningsdata fra laserskanning. Spesifikasjonen ble benevnt FKB-LedningLaser. Denne spesifikasjonen utgår og erstattes av Produktspesifikasjon Punktsky versjon 1.0, som blant annet omhandler klassifisering av ledningsobjekter fra punktskydata, og en ny Registreringsinstruks Punktsky FKB-Ledning som spesifiserer vektorisering av punktskydata til luftlinje, jordingsledning og generert senterpunkt for mast. Disse objekttypene inngår i Produktspesifikasjon FKB-Ledning.

Sammen med disse punktsky dokumentene sendes også fotogrammetrisk registreringsinstruks for Elveg 2.0 på høring.

Frist for å gi høringsinnspill er *10. desember 2021*

Høringsinnspill fylles inn i følgende https://www.kartverket.no/globalassets/geodataarbeid/standardisering/prosjekter/horinger/kommentarskjema-ved-horing.docx[skjema] – ett skjema per høringsdokument. 
Høringsinnspill sendes til standardiseringssekretariatet@kartverket.no


== Høringsdokumenter

=== Produktspesifikasjon: Punktsky 1.0
Punktsky 1.0 er ikke en revisjon og må ansees som en ny produktspesifikasjon. Men kravene til klassisk flybåren LiDAR (5p og 2p) videreføres uten større endringer og vi ser ikke at Punktsky 1.0 vil påvirke kostnad og gjennomføring av kartlegging. Ellers så introduseres følgende:

* Rammeverk for bestilling av Bathymetrisk LiDAR, Bathymetrisk Sonar (MBES), Terrestrisk LiDAR og Punktskyer fra Bildematching. Det er viktig at aktører som tilbyr disse tjenestene studerer krav til nøyaktighet og tetthet og påser at disse er satt korrekt for standard sensorer i markedet
* Leveranseformat løftes til LAS 1.4 (komprimert til LAZ)
Tilbydere av datasett må påse at de kan levere på 1.4 format.
* Alternativ tetthetsberegning før datasett med høy tetthet. 
Vi har erfart at vår tidligere tilnærming til test av punkttetthet (tetthet skal være innfridd for 95% av 10mx10m) har vært utfordrende i prosjekt med eksplisitte krav til punkttetthet. Vi har derfor introdusert en alternativ metode som sikrer en jevnere distribusjon av områder uten møtt tetthet i tillegg til at testvinduet er krympet inn til 2x2. Vi ønsker tilbakemelding på denne tilnærmingen og tar gjerne imot alternative metoder.

.Høringsdokumenter for Punktsky 1.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Produktspesifikasjon Punktsky 1.0 (HTML)
|{SOSITEST}/..
|2021-11-19

|Produktspesifikasjon Punktsky 1.0 (PDF)
|{SOSITEST}/..
|2021-11-19

|===


=== Registreringsinstruks: Punktsky FKB-Høydekurve 5.0
Spesifikasjonen omfatter høydekurve, forsenkningskurve, toppunkt, forsenkningspunkt, terrenglinje og terrengpunkt. 

Registreringsinstruksen er endret fra å være en fotogrammetrisk registreringsinstruks til instruks for generering av høydekurver fra en terrengmodell basert på punktskyer fra laserskanning eller bildematching.

.Høringsdokumenter for Punktsky FKB-Høydekurve 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Registreringsinstruks for Punktsky FKB-Høydekurve 5.0 (HTML)
|{REGINST}/..
|2021-11-19

|Registreringsinstruks for Punktsky FKB-Høydekurve 5.0 (PDF)
|{REGINST}/..
|2021-11-19

|===

=== Registreringsinstruks: Punktsky FKB-Ledning 5.0
Spesifikasjonen omfatter luftlinje, jordingsledning og generert senterpunkt for mast. Spesifikasjonen fokuserer på vektorisering av høyspentanlegg, men den er også mulig å benytte på lavspent og tele.
 
I et laserskanningsprosjekt kan det være aktuelt å klassifisere og vektorisere andre objekter også, samt utføre diverse analyser. For eksempel kan det være aktuelt å analysere om det er vegetasjon som er så nær fasene at det må utføres skogrydding eller lage en spesialleveranse til Nasjonalt Register for Luftfartshinder (NRL) basert på vektoriserte data. Slike spesialleveranser er ikke beskrevet i denne spesifikasjonen.
Spesifikasjon av klassifisering og leveranse av laserdata for ledninger finnes i Produktspesifikasjon Punktsky 1.0. Beskrivelse av laserskanning som datafangstmetode finnes i standarden Produksjon av basis geodata.

I høringen er det spesielt ønskelig med tilbakemelding på følgende:

* Er det aktuelt/ønskelig å registrere flymarkør fra punktskydata?
* Er kvalitetskravene fornuftige?
* Er det aktuelt å benytte denne registreringsinstruksen til ajourføring/oppgradering av FKB-Ledning, eller er kun nykartlegging tilstrekkelige?

.Høringsdokumenter for Punktsky FKB-Ledning 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Registreringsinstruks for Punktsky FKB-Ledning 5.0 (HTML)
|{REGINST}/..
|2021-11-19

|Registreringsinstruks for Punktsky FKB-Ledning 5.0 (PDF)
|{REGINST}/..
|2021-11-19

|===

=== Registreringsinstruks: Fotogrammetrisk FKB-Elveg 2.0
Produktspesifikasjon for Elveg 2.0 er første versjon av sitt slag og er en videreutvikling av datasettene FKB-Vegnett, Vbase og Elveg.

Selve registreringsinstruksen for fotogrammetrisk ajourhold av FKB-Elveg 2.0 er bygd på siste fotogrammetriske registreringsinstruks for Vegnett (4.61) tilpasset produktspesifikasjonen for Elveg 2.0.

Fotogrammetrisk FKB-Elveg 2.0 henger tett sammen med fotogrammetrisk registreringsinstruks for FKB-Veg 5.0 og FKB-TraktorvegSti 5.0. 

Fra versjon FKB 5.0 er alle typevegene (unntatt traktorveg og sti) flyttet fra FKB-TraktorvegSti til Elveg 2.0. Trapper som tilhører sti ligger også igjen i FKB-TraktorvegSti og har fått nytt navn (stitrapp).

Noen av de nye typevegene for FKB-Elveg 2.0 kan være vanskelige å registrere fotogrammetrisk og det ønskes spesiell tilbakemelding på om dette fremgår på en tydelig måte og at løsningene som er foreslått faller naturlig.

Det er gjort et forsøk på å beskrive mange ulike situasjoner med de forskjellige typevegene men vi ønsker tilbakemelding på om det er noen spesielle situasjoner som bør beskrives på en bedre måte eller som ev. Mangler.

Vi ønsker også en tilbakemelding på om koding av synbarhet er tilstrekkelig forklart i instruksen.

.Høringsdokumenter for Fotogrammetrisk FKB-Elveg 2.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Registreringsinstruks for Fotogrammetrisk FKB-Elveg 2.0 (PDF)
|{REGINST}/..
|2021-11-19

|===
