== Innspill til endringer i Produktspesifikasjon Punktsky 1.0 2022-01-01

[cols="10,15,40,35", options="header"]
|===
|Når
|Fra hvem
|Innspill
|Foreløpig kommentar

| 04.02.2022
| Christian.Malmquist@kartverket.no
| Tabell 6 Bildematching - Nøyaktighetskrav: 

Feil i "horisontal nøyaktighet" / "minimum tetthet"

| Løsning 


Fra 0,20-0,25 til 0,20-0,50



| 04.02.2022
| Andreas.Prebensen.Korsnes@kartverket.no
| Tabell 6 Bildematching - Nøyaktighetskrav: 

Jeg er ikke sikker på at kravet på systematisk avvik på bildematching med middels tetthet i produktspesifikasjonen Punktsky er stor nok for GSD 10 cm. For det kan være avvik i AT-en og i tillegg så blir det vanligvis ekstra avvik i høyde på bildematchinga. Så det kan være noen bildematchinger av GSD 10 cm som kan ha systematisk høydeavvik større enn 18 cm.

| Svar på epost 04.02.2022 

Nøyaktighetsskrankene for bildematching er alle arvet fra Lantmäteriet sin HML Höyddata (v2017). Når rammeverket for Punktsky ble satt opp hadde vi ikke gode nok erfaringstall og da Metria/Lantmäteriet har erfaring med bildematching gikk jeg for disse tallene som en start. Vi bør i løpet av 2022 vurdere faktisk nøyaktighet fra matching av Geovekstprosjekt. 



|===
