:title-separator: {sp}|
= SOSI standardisert produktspesifikasjon: FKB-Ledning – 5.0
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:appendix-caption: Vedlegg
:pdf-page-size: A4

<<<

== Innledning, historikk og endringslogg
=== Innledning
FKB-Ledning er en del av Felles Kartdatabase (FKB). FKB-spesifikasjonen er en serie 
produktspesifikasjoner for detaljerte basis geodata som samles inn og forvaltes gjennom 
Geovekst. Generelle beskrivelser for alle FKB-spesifikasjonene er samlet i FKB-Generell del.

FKB-Ledning omfatter ledningsdata innenfor elektrisitet, elektrisk kommunikasjon, 
belysningsanlegg og ledningsanlegg tilknyttet bane. Det er kun objekter som er synlig i 
terrenget (ligger over bakkenivå) som inngår i produktspesifikasjonen. 
Produktspesifikasjonen er tenkt benyttet ved datafangst av ledningsobjekter og som et 
grunnlag for distribusjon av FKB-data.

FKB-Ledning versjon 4.6 baserer seg på generelle konsepter definert i SOSI del 1 versjon 
4.5 og SOSI del 2 Ledning versjon 4.5.

=== Historikk
=== Endringslogg

// Metadata om produktspesifikasjonen

<<<

== Definisjoner og forkortelser
TIP: PSV avsnitt 4.Kap 2 viser til standardisert måte å skrive definisjoner (og implisitt forkortelser) på. 

=== Definisjoner
=== Forkortelser

== Generelt om spesifikasjonen
=== Unik identifisering

[TIP]
======
Identisk med tag 'SOSI_kortnavn' på pakka i EA.

Er case-sensitiv i SOSI-kontroll.

Norske tegn er ok hvis enkoding er riktig innstilt. Kontakt standardiseringssekretariatet hvis du har problemer med norske tegn.

======

==== Fullstendig navn
TIP: Identisk med tag på pakka i EA for SOSI_langnavn.

==== Versjon
TIP: Identisk med tag på pakka i EA for version.

=== Referansedato
TIP: PSS og PSV er litt uklare på hva referansedato er. Det er nevnt gyldighetsdato og utgivelsesdato.

=== Ansvarlig organisasjon

=== Språk

=== Hovedtema
TIP: Fritekst som beskriver hovedtema. Gjerne inspirert av DOK-hovedkategorier eller nasjonal temainndeling: https://register.geonorge.no/subregister/metadata-kodelister/kartverket/nasjonal-temainndeling

=== Temakategori
TIP: Temakategorier er en kodeliste i NS-ISO 19115. Hvis du ikke har tilgang til 19115, finner du en tabell i PSS avsnitt 13.5.2. Det angis én eller flere av kodene i tabellen for temakategorier.

=== Sammendrag

=== Formål
[TIP]
======
PSV har gjemt dette punktet i 4.Kap 3.5/3.6/3.7.

Note: NS-ISO 19131 har som utgangspunkt at en produktspesifikasjon er en bestilling av en (framtidig) geodataleveranse, men det nevnes også at produktspesifikasjoner kan dokumentere eksisterende geodata (noe som er vanlig i Norge).

Brukstilfeller:
Som regel er det behov for dokumentasjon av brukstilfeller som et produkt er tenkt for. En oversiktlig liste med navnene til relevante brukstilfeller kan plasseres under formålskapittelet. Flere detaljer for de nevnte brukstilfellene kan samles i et vedlegg. 
 
I PSS nevnes ikke brukstilfeller, men det er naturlig å plassere de her. En framtidig versjon av ISO 19131 vil ta høyde for det og gi standardiserte føringer for hvor og hvordan brukstilfeller skal dokumenteres.

======

=== Representasjonsform
[TIP]
======
PSV har gjemt dette punktet i 4.Kap 3.5/3.6/3.7.

PSS avsnitt 13.7 har en tabell med mulige verdier.

======

=== Datasettoppløsning
*Målestokktall*

*Distanse*

=== Utstrekningsinformasjon
TIP: Se 3.12 og 4.1.

*Utstrekningbeskrivelse*

*Geografisk område*

*Vertikal utbredelse*

*Innhold gyldighetsperiode*

=== Identifikasjonsomfang
TIP: Dette punktet er litt uklart i PSS og PSV. I ISO-standarden for produktspesifikasjoner (NS-EN ISO 19131) er det krav om at identifikasjonen (hele kapittel 3 i denne malen) skal ha en link til den delen av spesifikasjonsomfanget som gjelder hele produktspesifikasjonen (ofte avsnitt 4.1 i denne malen). Forslag til utfylling kan være "hele datasettet" eller "Som angitt i avsnitt 4.<x>.".

=== Supplerende beskrivelse
TIP: Dette punktet er gjemt i PSS 13.6.3 og i PSV 4.Kap 3.12.

== Spesifikasjonsomfang
(Antall spesifikasjonsomfang: [yellow-background]#<sett inn antall># )
[TIP]
======
Dette kapittelet beskriver omfang (scopes) i produktspesifikasjonen. Vanligvis vil det være ett omfang, "hele datasettet", som angis i avsnitt 4.1. Merk at 4.1.5 blir gjentagelse fra avsnitt 3.11.

Det kan defineres spesifikasjonsomfang for deler av datasettet, og disse angis i avsnitt 4.2-4.x. Andre spesifikasjonsomfang er nødvendig hvis produktspesifikasjonens (kapittel 5 og utover) har spesifikasjoner som bare gjelder deler av datasettet. I så fall må det refereres til identifikasjonen spesifisert her i kapittel 4.
======

=== Spesifikasjonsomfang for hele spesifikasjonen
[TIP]
======
Se 3.11 og 3.12.

Identiske omfang trenger ikke gjentas.
======

==== Identifikasjon

==== Nivå

==== Navn

==== Beskrivelse

==== Utstrekningsinformasjon
*Utstrekning beskrivelse*

*Geografisk område*

*Vertikal utbredelse*

*Innhold gyldighetsperiode*

=== (Spesifikasjonsomfang for deler av spesifikasjonen)

==== (Identifikasjon)

==== (Nivå)

==== (Navn)

==== (Beskrivelse)

==== (Utstrekningsinformasjon)
*(Utstrekning beskrivelse)*

*(Geografisk område)*

*(Vertikal utbredelse)*

*(Innhold gyldighetsperiode)*

== Innhold og struktur
TIP: *Eksport fra EA legges inn her*

== Referansesystem
(Antall lovlige romlige koordinatsystem for dette produktet: [yellow-background]#<sett inn antall># )

TIP: Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

=== Romlig referansesystem [yellow-background]#<trenger vi en id her?>#

==== Omfang

==== Navn på kilden til referansesystemet:

==== Ansvarlig organisasjon for referansesystemet:

==== Link til mer info om referansesystemet:

==== Koderom:

==== Identifikasjonskode:

==== Kodeversjon 

=== (Romlig referansesystem [yellow-background]#<trenger vi en id her?># )

==== (Omfang)

==== (Navn på kilden til referansesystemet:)

==== (Ansvarlig organisasjon for referansesystemet:)

==== (Link til mer info om referansesystemet:)

==== (Koderom:)

==== (Identifikasjonskode:)

==== (Kodeversjon)

=== (Temporalt referansesystem)

==== (Navn på temporalt referansesystem

==== (Omfang)

== Kvalitet

[TIP]
=====
Dette kan være et vanskelig kapittel. Det første du bør gjøre er å sjekke hva du anførte som formål i avsnitt 3.8. Hvis du skal bestille data, er det mest naturlig om du her angir kvalitetskrav. Hvis du dokumenterer eksisterende geodata, derimot, bør kvaliteten her beskrive geodataene.

PSS kapittel 17 gir en innføring i kvalitet. Ofte innebærer kvalitet en statistisk analyse av kontrollmålinger av geodata. Hvis dette er helt ukjent for deg, kan du kanskje anføre at geodataene ikke er kontrollert.

Kvalitet kan også angis kvalitativt (noe NS-ISO 19115 og andre også omfatter). Det kan for eksempel være at geodataene er registrert etter en innmålingsinstruks, eller at de er resultat av beregninger beskrevet i en teknisk rapport eller vitenskapelig artikkel. Merk at dette er nært knyttet til kapittel 8.

Kvalitet skal også referere til omfang (scopes) angitt i kapittel 4. I tillegg kan du innenfor kvalitet også spesifisere enkelte deler (også scope), og angi ulike kvaliteter. Merk at norske geodata (SOSI-standarden) har mulighet for kvalitetsangivelse på objekttypene, men slike hører eventuelt hjemme i kapittel 5.

Hvis du (eller din organisasjon) ikke har peiling på kvaliteten til geodataene, er dette nyttig kvalitetsinformasjon som bør nevnes.

Kvalitetsinformasjon skal oppgis for hver av de fem kvalitetselementene som er oppgitt i PSV:

* Fullstendighet
* Stedfestingsnøyaktighet
* Egenskapsnøyaktighet
* Tidfestingsnøyaktighet
* Logisk konsistens

Dersom det for et kvalitetselement ikke er mulig å angi noen fornuftig informasjon skal dette oppgis sammen med en forklaring på årsaken.

=====

== Datafangst
[TIP]
=====
Datafangst skal også referere til omfang (scopes) angitt i kapittel 4.

Datafangst kan være nært knyttet til kapittel 7.

=====

== Datavedlikehold
TIP: Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4. 

=== Vedlikeholdsinformasjon [yellow-background]#<trenger vi en id her?>#
==== Omfang 

==== Vedlikeholdsfrekvens 


==== Vedlikeholdsbeskrivelse 


=== (Vedlikeholdsinformasjon [yellow-background]#<trenger vi en id her?>#)

==== (Omfang)

==== (Vedlikeholdsfrekvens)

==== (Vedlikeholdsbeskrivelse)

== Presentasjon
TIP: Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

=== Omfang

=== Referanse til presentasjonskatalog

== Leveranse
TIP: Merk at "Omfang" skal referere til omfang (scopes) angitt i kapittel 4.

=== Leveransemetode [yellow-background]#<trenger vi id her?>#

==== Omfang

==== Leveranseformat
*Formatnavn*

*Formatversjon* 

*Formatspesifikasjon*

*Filstruktur*

*Språk*

*Tegnsett*

==== Leveransemedium
*Leveranseenhet*

*Overføringsstørrelse*

*Navn på medium*

*Annen leveranseinformasjon*

=== (Leveransemetode [yellow-background]#<trenger vi id her?>#)

==== (Omfang)

==== (Leveranseformat)
*(Formatnavn)*

*(Formatversjon)* 

*(Formatspesifikasjon)*

*(Filstruktur)*

*(Språk)*

*(Tegnsett)*

==== (Leveransemedium)
*(Leveranseenhet)*

*(Overføringsstørrelse)*

*(Navn på medium)*

*(Annen leveranseinformasjon)*

== Tilleggsinformasjon
TIP: Merk at tilleggsinformasjon skal referere til omfang (scopes) angitt i kapittel 4.

== Metadata
[TIP]
=====
Merk at metadata skal referere til omfang (scopes) angitt i kapittel 4.

Merk også at du her skal angi hvilke metadata som skal følge produktet, men ikke selve metadatene.

=====

=== Omfang

=== Metadataspesifikasjon

[appendix]
== SOSI-format-realisering
TIP: Dersom SOSI-format er angitt under leveranseformat i kapittel 11, klippes inn SOSI-format-realiserings-rapport

[appendix]
== GML-realisering
TIP: Dersom GML er angitt som leveranseformat i kapittel 11, skal det her angis hvordan applikasjonsskjemaet skal realiseres i GML i form av URL

[appendix]
== Annen nyttig informasjon til brukere
TIP: Informasjon, fortrinnsvis av informativ art, som kan være nyttig for brukere, samles i egne vedlegg
