=== UML-modell for Fotogrammetriske registreringsinstrukser

For å sørge for at det er fullt samsvar mellom FKB produktspesifikasjonene og registreringsinstruksene for datafangst er det utarbeida et opplegg 
med egne UML-datamodeller for registreringsinstruksene. I korte trekk går dette ut på at det tas en kopi av UML datamodellen for FKB produktspesifikasjonene der det legges inn justeringer og ekstrainformasjonen med tanke på datafangst. Disse UML-modellene følger ikke noen SOSI-standard, men er utarbeide med tanke på å kunne generere ut godt lesbar dokumentasjon og maskinlesbare filer for validering (SOSI-kontroll, GML-skjema etc.). UML datamodellene finnes i SOSI modellregister.

Registreringsinstruksene består av UML-elementer (https://sosi.geonorge.no/veiledere/uml/[se veiledning for å lese UML-diagrammer]). Alle objekttyper listes derfor ut som "FeatureType" slik de er modellert i UML. Assosiasjoner i FKB listes i registreringsinstruksene ut i egenskapstabellen (med en FeatureType som datatype). I forbindelse med fotogrammetrisk registrering vil hovedregelen være at assosiasjoner håndteres som opsjonelle egenskaper, dvs. at de ikke registreres.


=== Informasjon som angis om alle objekttyper

* Definisjon hentet fra FKB-produktspesifikasjon
* Bilde/skisse hentet fra FKB-produktspesifikasjon
* Tilleggsbeskrivelse for objekttypen for fotogrammetrisk registrering
* Bilder/skisser med bildetekst for fotogrammetrisk registrering
* Tabell med *Føringer* for fotogrammetrisk registrering. Se tabell under for en forklaring på hvilke føringer som kan være angitt og hva disse betyr.  
* Egenskapstabell hentet fra FKB-produktspesifikasjon. Denne inneholder alle egenskaper for objekttypen. Både de som skal registreres fotogrammetrisk og alle andre.
* Tabell med *Restriksjoner* er angitt for noen objekttyper. Denne tabellen inneholder egenskaper det er knyttet spesielle krav til ved fotogrammetrisk registrering.
* For objekttyper med egenskaper som benytter kodelister der disse kodeverdiene skal klassifiseres fotogrammetrisk finnes det også *Presiseringer til beskrivelsen av kodelistekoder*. Her listes de aktuelle kodene for fotogrammetrisk registering ut med en definisjon/beskrivelse som skal ligge til grunn for klassifiseringen og gjerne også forklarende bilder/skisser.


[[tab-foringer]]
.Føringer for registrering som er angitt i registreringsinstruksene
[cols="3*", options="header"]
|===

|Føring
|Verdier
|Kommentar

|FKB-A
|Registreres ikke / Opsjonell registrering / Påkrevd registrering
|Finnes på alle objekttyper

|FKB-B 
|Registreres ikke / Opsjonell registrering /Påkrevd registrering
|Finnes på alle objekttyper

|FKB-C 
|Registreres ikke / Opsjonell registrering /Påkrevd registrering
|Finnes på alle objekttyper

|FKB-D 
|Registreres ikke / Opsjonell registrering /Påkrevd registrering
|Finnes på alle objekttyper

|FKB høydereferanse
|Fritekst som angir høydereferanse for registrering av geometrien til objekttypen
|Finnes på alle objekttyper

|FKB grunnrissreferanse
|Fritekst som angir grunnrissreferanse for registrering av geometrien til objekttypen
|Finnes på alle objekttyper

|FKB-A minstestørrelse
|Fritekst som angir minstestørrelse for registrering i FKB-A
|Finnes bare på objekttyper der det er minstestørrelser for registrering

|FKB-B minstestørrelse
|Fritekst som angir minstestørrelse for registrering i FKB-B
|Finnes bare på objekttyper der det er minstestørrelser for registrering 

|FKB-C minstestørrelse
|Fritekst som angir minstestørrelse for registrering i FKB-C
|Finnes bare på objekttyper der det er minstestørrelser for registrering

|FKB-D minstestørrelse
|Fritekst som angir minstestørrelse for registrering i FKB-D
|Finnes bare på objekttyper der det er minstestørrelser for registrering

|FKB registeringsmetode
|Fritekst som angir krav til registreringsmetode for objekttypen
|Finnes bare på objekttyper der dette er relevant

|===

*Merknad:* Føring for minstestørrelser gjelder automatisk for en mindre detaljert FKB-standard. Dersom det bare er angitt krav til minstestørrelser i FKB-A gjelder denne automatisk også for de mindre detaljerte FKB-standardene om ikke annet er spesielt angitt.

