
== Fotogrammetrisk nykonstruksjon

Ved fotogrammetrisk nykonstruksjon skal alle objektene som er spesifisert i registreringsinstruksen og som er synlige i flybildene registreres. 

=== Registrering av nye kartobjekter

Hovedregelen er at påkrevde objekttyper registreres, mens opsjonelle objekttyper ikke registreres.

Unntak fra hovedregelen kan avtales i det enkelte kartleggingsprosjektet.

=== Registrering av egenskaper på nye kartobjekter 

Hovedregelen er at obligatoriske egenskaper registreres, mens opsjonelle egenskaper ikke registreres ved fotogrammetrisk datafangst.

Egenskaper som skal registreres/klassifiseres ved hjelp av fotogrammetri er beskrevet spesielt i registreringsinstruksen. Øvrige egenskaper er ikke nevnt i registreringsinstruksen. 

Følgende egenskaper håndteres spesielt:

* Egenskapen _Identifikasjon_ skal ikke legges inn på objektene
* Egenskapen _Oppdateringsdato_ skal ikke legges inn på objektene
* Alle objekter skal ha egenskapene _Nøyaktighet_ og _NøyaktighetHøyde_ som del av datatypen Posisjonskvalitet
* Alle objekter skal ha egenskapen _Registreringsversjon_

Unntak fra hovedreglene kan spesifiseres under den enkelte objekttype/egenskap i den enkelte registreringsinstruks eller i teknisk spesifikasjon for kartleggleggingsprosjektet.

==== Obligatoriske egenskaper med kodelister 

En del egenskaper med kodelister er angitt som påkrevde. Dette krever at det legges på en verdi ved fotogrammetrisk registrering. For slike egenskaper skal det være definert en "standardverdi" som benyttes i de tilfellene det ikke er angitt noe annet. Konkrete regler for hvordan dette skal registreres for de enkelte objekttyper/egenskaper skal være angitt i registreringsinstruksen. Egenskapene _Medium_ og _Høydereferanse_ (HREF) er benyttet på mange objekter i flere FKB-datasett og for disse gjelder følgende generelle regler dersom ikke annet er spesielt angitt:

[[tab-medium]]
.Registrering av verdier for egenskapen Medium der ikke annet er spesifisert
[cols="2*", options="header"]
|===

|Kodeverdi
|Forklaring

| T  (på terrenget)
| Standardverdi. Benyttes for alle objekter der det ikke er grunn til å benytte en annen verdi

| U (under bakken)
| Benyttes for objekter under bruer etc. der det ikke er direkte innsyn med fotogrammetri, men krav til gjennomgående registrering av objektet

| L (i lufta)
| Benyttes for objekter på bruer/bygninger etc.
|===

[[tab-href]]
.Registrering av verdier for egenskapen Høydereferanse der ikke annet er spesifisert
[cols="2*", options="header"]
|===

|Kodeverdi
|Forklaring

| TOP  (toppen av objektet)
| Standardverdi ved fotogrammetrisk registrering. For de fleste objektertyper dette også presisert på objekttypen

| FOT (foten av objektet)
| Benyttes ved fotogrammetrisk registrering kun for objekttyper der det er presisert at høydereferansen skal være foten av objektet
|===


== Fotogrammetrisk ajourhold

Ved fotogrammetrisk ajourhold skal eksisterende situasjon bringes ajour med oppdatert situasjon i terrenget ved fotograferingstidspunkt. Oppdragsgiver sender eksisterende data i henhold til FKB-produktspesifikasjon til oppdragstaker som grunnlag for ajourføring.

Dette innebærer i prinsippet følgende operasjoner:

. Registrere nye objekter der disse finnes i flybildene, men ikke i eksisterende data. Reglene som gjelder nye objekter ved <<Fotogrammetrisk nykonstruksjon>> skal da anvendes.
. Verifisere at objekter som er registrert i eksisterende data fortsatt er i tråd med datagrunnlaget/flybildene. For disse objektene skal egenskapen VERIFISERINGSDATO oppdateres, men forøvrig skal objektene ikke endres. Se {fkbGenerellDel-url}/#truebruk-av-datoegenskaper[beskrivelse av håndtering av datoegenskaper i FKB Generell del] for mer om dette.
. Slette objekter som finnes i eksisterende data, men som ikke finnes i flybildene. 

Unntak fra/presisering av hovedregelen kan avtales i teknisk spesifikasjon for kartleggingsprosjektet.

== Fotogrammetrisk oppgradering

Mens _ajourføring_ dreier seg om å fange opp endringer i terrenget som ikke finnes i FKB-dataene dreier en _oppgradering_ seg om en total gjennomgang av alle data innenfor kartleggingsområdet for å sikre at de er i tråd med spesifiserte krav. Eksempler på oppgradering kan være:

* Omklassifisering av angitte objekttyper i tråd med nye regler/krav i FKB-produktspesifikasjon
* Oppgradering av angitte objekttypers geometrirepresentasjon (f.eks. hvis det bestemmes at en objekttype skal endres fra HREF FOT til HREF TOP)
* Påføring av egenskaper på alle objekter av en objekttype
* Påføring av høydeverdier på alle objekter av en objekttype
* Tilpasning av angitte objekttyper for å skape konsistens mellom datasett (f.eks. en omkoding av eksisterende data i FKB-Veg for å skape konsistens med vegnettet)

Reglene for oppgradering er ikke beskrevet i fotogrammetrisk registreringsinstruks og må avtales spesielt i det enkelte kartlegginsprosjekt der dette er aktuelt. 
