:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb

[[def-ajourføring]]
.ajourføring
korrigering av innholdet i geodataene slik at de fremstiller de faktiske forhold på et gitt tidspunkt, etter de retningslinjer som gjelder for innhold og kvalitet [PABG]

_MERKNAD_: Det er en selvfølge at ”konsekvensrettelser” også blir utført. For eksempel når det bygges et nytt hus, blir ofte gjerder, arealbruksgrenser og veger omkring huset forandret. Ajourføring innebærer at alle disse forandringene blir gjort i de aktuelle databaser.
Oppgradering til nyere og bedre standard defineres som noe annet enn ajourføring, selv om det kan gjøres på samme tidspunkt som periodisk ajourføring.

[[def-applikasjonsskjema]]
.applikasjonsskjema
informasjonsmodellene i SOSI-modellregister er modellert som UML-modeller. UML-modellen for et FKB-datasett benevnes som et UML-applikasjonsskjema. Fra UML-applikasjonsskjema kan det automatisk genereres et GML-applikasjonsskjema som beskriver hvordan dataene representeres som GML.

_MERKNAD_: Se objektkatalog

[[def-avledet datasett]]
.avledet datasett
bearbeidede primærdata tilpasset et bestemt bruksområde [FKB]

_MERKNAD_: Avledede data skal i prinsippet ikke ajourføres direkte, men ajourføringen skal komme gjennom automatisk utvelgelse og generalisering fra primærdata. I noen tilfeller vil dette være en for tung prosess slik at en må avvike fra hovedprinsippet. 
	Kalles også generalisert datasett.

EKSEMPEL 	N5 Kartdata (avledet/generalisert produkt fra FKB).

basis geodata
Detaljerte geodata som beskriver det fysiske landskapet ved naturlige eller menneskeskapte objekter. Basisdata brukes til lokalisering og som underlag for temadata. [FKB]

MERKNAD	basis geodata er synonymt med begrepet grunnkart (eller grunnkartdata)


datasett
identifiserbar samling av beslektede data [G]

egenskap 
navngitt kjennetegn eller karakteristikk av et objekt

MERKNAD	Egenskap defineres ved navn (for eksempel "bygge-år"), datatype (for eksempel årstall) og verdiområde (for eksempel "Kristi fødsel - dags dato").
Egenskapsverdi er verdien til egenskapen for det aktuelle objektet, for eksempel 1998. Egenskapsdata kalles noen ganger for attributtdata.

egenskapsnøyaktighet 
uttrykk for hvor godt egenskapsdataene beskriver de aktuelle egenskapene [G]

FKB
FKB er en forkortelse for Felles Kartdatabase. Se kapittel 1 for en beskrivelse av FKB.

Fotogrammetrisk FKB
FKB-data som er etablert ved fotogrammetrisk kartlegging [FKB] 

MERKNAD	I Fotogrammetrisk FKB inngår også enkelte objekttyper som ikke registreres fotogrammetrisk. Eksempel er fiktive avgrensningslinjer og representasjonspunkt.

grunnkart 
Grunnkart er et begrep som er synonymt med basis geodata. Se definisjon under basis geodata. 

MERKNAD	Grunnkart brukes til flere formål og kan danne grunnlag for avledede kart i forskjellige målestokker. Grunnkartet skal være det kartgrunnlaget som skal tjene alle formål som omhandles i plan- og bygningsloven eller dens forskrifter. 


fullstendighet 
uttrykk for i hvilken grad spesifiserte deler av et produkt finnes i det aktuelle datasettet [G]

MERKNAD	Fullstendighet karakteriseres ved kvalitetsmålene manglende objekter, overskytende objekter (ønsket om fullstendige geodatabaser innebærer også at det er galt dersom det finnes objekter i databasene som ikke skal være der i henhold til spesifikasjonene) og manglende egenskaper.
Fullstendighet kan angis i prosent i relasjon til spesifiserte krav.
Informasjon om fullstendighet må være datert.

geodata 
stedfestet informasjon [G]

MERKNAD	Geodata består av objektidentifikasjon og informasjon om stedfesting og egenskaper. Stedfestingsdataene på sin side kan omfatte både posisjonsdata og geometriske beskrivelsesdata.

kart 
generalisert avbildning av geografiske objekter med deres romlige relasjoner; med angitt geodetisk datum, projeksjon og koordinatsystem, samt målestokk dersom avbildningen er analog [G]

kartdata 
geodata tilrettelagt for presentasjon av kart [PABG]

kontinuerlig ajourhold
fortløpende ajourføring basert på rapportering fra forvaltningsrutiner, daglige arbeidsrutiner og samarbeidsparter [PABG]

MERKNAD	Kalles også administrativt vedlikehold. Data som samles inn administrativt, kan være digitale stikningsdata eller data fra sluttkontroll av beliggenhet, koordinatfestede grensemerker, markmålte bygninger, senterpunkt bygning, situasjonsplan og melding om landbruksbygg.

kvalitet
i hvilken grad en samling av iboende egenskaper oppfyller krav  [G]

MERKNAD	I standarden Geodatakvalitet for en nærmere beskrivelse av datakvalitet. 

logisk konsistens
hvor godt regler som finnes i spesifikasjonene, er oppfylt [G]

MERKNAD 	Logisk konsistens betegner sammenhengen mellom produktet og reglene produktet skal oppfylle. Logisk konsistens kan altså måles uten at en kjenner noen "fasit". 

EKSEMPEL	I SOSI er det spesifisert hvordan en flate skal representeres i en SOSI-fil. Samme regel gjelder for FKB. I SOSI er det også beskrevet hvilke egenskaper for eksempel en vegkant skal ha. De samme egenskaper, eller et utvalg av disse, skal vegkant ha i FKB.

metadata 
informasjon som beskriver et datasett [G]

MERKNAD 	Hvilke opplysninger som inngår i metadataene, kan variere avhengig av datasettets karakter. Vanlige opplysninger er innhold, kvalitet, tilstand, struktur, format, produsent og vedlikeholdsansvar.

nøyaktighet 
mål for en estimert verdis nærhet til sin sanne verdi eller til det man antar er den sanne verdi [G]

MERKNAD 	Den estimerte verdien er vanligvis målt eller beregnet. I standarden Geodatakvalitet er de ulike nøyaktighetsmålene beskrevet.

objekt 
forekomst (instans) av en objekttype [SOSI]

objektkatalog
definisjon og beskrivelse av objekttyper, objektegenskaper samt relasjoner mellom objekter, sammen med eventuelle funksjoner som er anvendt for objektet [SOSI] 

EKSEMPEL	SOSI-Objektkatalog

objekttype 
geografisk objekttype
en klasse av objekter med felles egenskaper, forholdet mot andre objekttyper og funksjoner [SOSI] 

EKSEMPEL	Eksempler på objekttyper er Takkant, Arealbruksgrense og Mønelinje. 

områdetype
arealinndeling basert på krav til detaljering/nøyaktighet av basis geodata i området [FKB] 

MERKNAD	I FKB brukes områdetypen til å si noe om hvilken FKB-standard som bør velges i området (se punkt 5.2). Områdetype brukes også som styrende for krav i standardene "Plassering og beliggenhetskontroll" og "Stedfesting av matrikkelenhets- og råderettsgrenser".

oppgradering
forbedring av den datatekniske kvaliteten av eksisterende data [PABG] 

periodisk ajourhold
ajourføring som utføres systematisk med jevne mellomrom [PABG] 

MERKNAD	Ved periodisk ajourføring blir eksisterende data, enten de har vært gjennom kontinuerlig ajourføring eller ei, kontrollert og evt. forbedret, og manglende objekter blir supplert. Objekter som ikke er endret, blir ikke kartlagt på nytt. Etter periodisk ajourføring skal datasettene minimum tilfredsstille kvalitetskravene for den valgte FKB-standard i området. Det kan være nødvendig også med en oppgradering for å oppfylle kvalitetskravene. Periodisk ajourføring gjøres vanligvis ved fotogrammetri.

presentasjonsdata
tilleggsdata til FKB som er nødvendige for å formidle en god presentasjon uten at de opprinnelige datasettene blir berørt [FKB]

MERKNAD	Presentasjonsdata lages for presentasjoner i ulike målestokker. Det genereres presentasjonsdata for å ha mulighet til blant annet å redigere, avblende/slette, skrive om eller flytte tekster og symboler i kartbildet, uten at datasettene blir berørt. 

EKSEMPEL	Eksempler på presentasjonsdata er tekstdata generert fra datasett der tekst, tall eller symboler er ferdig plassert i kartbildet. En annen type presentasjonsdata er avblendingspolygoner som brukes til å fjerne unødig mye data i et aktuelt kartbilde. 

primærdatasett
et definert geodatasett som består av de mest detaljerte og nøyaktige data innen et definert område, har en viss utbredelse og jevnlig blir produsert og/eller ajourholdt [G]

MERKNAD	Primærdatasett skal være presentasjons- og produktuavhengige. De skal kunne danne utgangspunkt for forskjellig bruk og forskjellige produkter. Det er derfor krav om en viss utbredelse og produksjon før en kan kalle et datasett for primærdatasett. Primærdatasett er i prinsippet uavhengige datasett (ikke avledet fra andre datasett) og ajourholdes uavhengig av andre datasett. Et objekt tilhører bare ett primærdatasett. Primærdatasett kodes og struktureres i henhold til SOSI Del 2, men kan være gitt strengere eller svakere krav til hva som er standard og hva som er valgfritt (opsjon) i datasettet.

produktspesifikasjon 
detaljert beskrivelse av ett datasett eller en serie med datasett med tilleggsinformasjon som gjør det mulig å produsere, distribuere og bruke datasettet av andre (tredjepart) [SOSI]

MERKNAD	En dataproduktspesifikasjon kan lages for produksjon, salg, sluttbrukervirksomhet eller annet.

standardavvik
statistisk størrelse som angir spredningen for en gruppe måle- eller beregningsverdier i forhold til deres sanne eller estimerte verdier [G]


topologi
beskrivelse av sammenhengen mellom geografiske objekter [G]

MERKNAD 	De aktuelle objektene har ofte en fysisk sammenheng. Topologi er de av objektenes egenskaper som overlever det som er kalt kontinuerlige transformasjoner (også kalt gummiduk-transformasjoner). Alle tallverdier (lengder, arealer og retninger) kan bli forandret, mens for eksempel naboskapsforhold vil være uendret.


