= Høringsnotat FKB 5.0
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb


CAUTION: Testversjon 2021-09-17

== Høring av FKB 5.0

=== Innledning

Om standardiseringsprosjektet, organisering, tidsramme etc.

=== Leseveileding

Litt om hvordan finne fram i dokumentene

=== Høringssvar

Høringsfrist

Bruk av skjema


=== Dokumenter som inngår i høringen

==== FKB Generell del

FKB generell del er definert som en SOSI abstrakt spesifikasjon

Link til dokument: http://skjema.geonorge.no/SOSITEST/fagomr%c3%a5destandard/FKB_generell/5.0/

Endringslogg: http://skjema.geonorge.no/SOSITEST/fagomr%c3%a5destandard/FKB_generell/5.0/#trueendringslogg

===== Spesielle forhold vi ønsker tilbakemelding på i forbindelse med høring

Noe spesielt i FKB-generell del?


==== FKB-Arealbruk

Generell kommentar...

Link til dokument: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/

Endringslogg: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/#trueendringslogg

===== Spesielle forhold vi ønsker tilbakemelding på i forbindelse med høring

Noe spesielt i FKB-Arealbruk?



==== FKB-Bygning

Generell kommentar...

Link til dokument: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/

Endringslogg: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/#trueendringslogg

===== Spesielle forhold vi ønsker tilbakemelding på i forbindelse med høring

Noe spesielt i FKB-Bygning?


==== FKB-BygnAnlegg

Generell kommentar...

Link til dokument: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/

Endringslogg: http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/#trueendringslogg

===== Spesielle forhold vi ønsker tilbakemelding på i forbindelse med høring

Noe spesielt i FKB-BygnAnlegg?


==== Til sammen 15 datasett osv. osv....