= Høringsnotat FKB 5.0
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb


CAUTION: Oppdatert 2021-09-24

== Høring av FKB 5.0

=== Innledning

Standardiseringsprosjektet har gjort en samlet gjennomgang av alle FKB-produktspesifkasjonene. FKB produktspesifkasjonene vil dermed få status som _standardiserte produktspesifikasjoner_. Standardiseringsprosjektet har også tatt for seg _FKB generell del_. Dette dokumentet foreslår vi nå å gi statusen _SOSI abstrakt spesifikasjon_ og inngår også i høringen.

Se https://www.kartverket.no/geodataarbeid/standardisering/prosjekter-og-horinger/produktspesifikasjon-fkb[artikkel om høringen på Kartverket.no] for mer om standardiseringsprosjektet, link til skjema for tilbakemelding etc. 

=== Leseveileding

==== Innhold i høringen

Videre nedover i dokumentet listes de ulike dokumentene som er ute på høring. Hvert dokument har en egen endringlogg som beskriver de viktigste endringene i dokumentet. Denne endringsloggen gjentas derfor ikke her i høringsdokumentet, men det er lagt inn en link direkte til endringsloggen i HTML-versjonen av dokumentet.

For hvert datasett/dokument har vi følgende dokumentasjon:

. En generell beskrivelse av hva som er endret i datasettet og om det er noen problemstillinger det ønskes spesielle tilbakemeldinger på i høringen.
. Link til PDF og HTML-versjon av dokumentet. 
. Link direkte til endringslogg
. Link til GML-Schema og generert GML eksempelfil
. Link til fotogrammetrisk registreringsinstruks (der det er relevant)

Fotogrammetrisk registreringsinstruks er ikke formelt en del av standardiseringsprosjektet og er å anse som et vedlegg i høringen. Registreringsinstruksene inneholder mye relevant ekstrainformasjon og er for en del viktige bruksområder av FKB det dokumentet man forholder seg til. Det er derfor vesentlig at man kan behandle også registreringsinstruksene som en del av høringen på FKB produktspesfikasjonene.

*Mer om det fotogrammetriske registreringsinstruksene og hvordan disse håndteres må beskrives...*

==== Hvordan lese FKB produktspesifikasjoner

FKB produktspesifikasjonene er basert på UML datamodeller. Produksjonsløypene for å hente dokumentasjon ut fra UML-modellene er endret i forbindelse med innføring av FKB 5.0. Dokumentene vil altså se noe anderledes ut selv om innholdet ikke er endret. De viktigste nyhetene når det gjelder formen på dokumentasjonen er følgende:

* HTML er hovedformatet for spesifikasjonen. Det er forsøkt lagt inn mange linker/referanser internt i dokumentene og ut til ressurser på utsiden. Det anbefales at man forholder seg til FKB produktspesifikasjonene som HTML for å få utbytte av dette.
* PDF er sekundærformatet. De som fortsatt ønsker seg en utskrift på papir kan printe PDF-varianten. 
* Både PDF og HTML inneholder en innholdsfortegnelse (synlig i venstre marg) som gjør det langt lettere å manøvrere rundt i dokumentene. Bruk denne!
* Veldig mye av FKB-produktspesifikasjonene er likt for alle datasettene. Mange kapitler er helt like. Det som er unikt for hvert FKB-datasett er i hovedsak:
** Kapittel 1: Beskrivesle av datasettet og endringslogg
** Kapittel 5: En beskrivelse av objekttyper og øvrige elementer i datamodellen (utlisting fra UML)
* Det er forsøkt å legge til en beskrivende bilde/skisse for flest mulig objekttyper i FKB

==== Endringslogger
I endringsloggene til hvert dokument har vi forsøkt å beskrive de viktigste endringene for hvert datasett. De generelle endringene for FKB er kun beskrevet i FKB generell del og ikke gjentatt i hvert enkelt datasett. 

Endringsloggene inneholder ikke en komplett oversikt over alle endringer på detaljnivå. For å få en forståelse av de reviderte FKB produktspesifikasjonene må man lese hele FKB produktspesifikasjonene. Om man har et tett forhold til eksisterende FKB produktspesifikasjoner bør imidlertid endringsloggen gi en god pekepinn på hva man bør se litt ekstra nøye på i forslag til reviderte spesifikasjoner. 


== Dokumenter som inngår i høringen

=== SOSI abstrakt spesifikasjon - FKB Generell del

FKB generell del er fra FKB 5.0 definert som en _SOSI abstrakt spesifikasjon_. Innholdet er i hovedsak det samme som i FKB 4.6 Generell del. Dokumentent er imidelertid omstrukturert noe i forbindelse med tilpasning til HTML som primærformat. 

_SOSI abstrakt spesifikasjon_ er en type spesifikasjon som ikke har klare krav knyttet til seg. Det finnes ingen mal for hva som skal beskrives i FKB Generell del. I forbindelse med høringen tar vi gjerne innspill på om det er innhold som burde vært beskrevt i FKB generell del, men som ikke er med i høringsversjon.

Endringslogg for FKB Generell del finner du http://skjema.geonorge.no/SOSITEST/fagomr%c3%a5destandard/FKB_generell/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB generell del 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|SOSI abstrakt spesifikasjon - FKB Generell del versjon 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/fagomr%c3%a5destandard/FKB_generell/5.0/
|2021-09-26

|SOSI abstrakt spesifikasjon - FKB Generell del versjon 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/fagomr%c3%a5destandard/FKB_generell/5.0/
|2021-09-26
|===


=== FKB-Arealbruk

Utover tilpasning til generelle endringer for FKB 5.0 er det gjort lite endringer i FKB-Arealbruk i forbindelse med revisjonen.

Endringslogg for FKB-Arealbruk finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Arealbruk 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Arealbruk 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Arealbruk 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Arealbruk/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===


=== FKB-AR5

Utover tilpasning til generelle endringer for FKB 5.0 er det gjort lite endringer i FKB-AR5 i forbindelse med revisjonen.

Endringslogg for FKB-AR5 finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-AR5/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-AR5 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-AR5 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-AR5/5.0/
|2021-09-25

|Standardisert produktspesifikasjon FKB-AR5 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-AR5/5.0/
|2021-09-25

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-AR5/5.0/
|2021-09-26

|GML eksempelfil
|
|2021-09-26


|===

=== FKB-Bane

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Bane finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bane/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Bane 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Bane 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bane/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Bane 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bane/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bane/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bane/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-BygnAnlegg

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-BygnAnlegg finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-BygnAnlegg 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-BygnAnlegg 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-BygnAnlegg 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-BygnAnlegg/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Bygning

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Bygning finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Bygning 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Bygning 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Bygning 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Bygning/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Høydekurve

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Høydekurve finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Høydekurve/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Høydekurve 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Høydekurve 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Høydekurve/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Høydekurve 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Høydekurve/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Høydekurve/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Høydekurve/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===


=== FKB-Ledning

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Ledning finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Ledning/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Ledning 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Ledning 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Ledning/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Ledning 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Ledning/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Ledning/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Ledning/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===


=== FKB-Lufthavn

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Lufthavn finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Lufthavn/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Lufthavn 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Lufthavn 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Lufthavn/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Lufthavn 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Lufthavn/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Lufthavn/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Lufthavn/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Naturinfo

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Naturinfo finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Naturinfo/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Naturinfo 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Naturinfo 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Naturinfo/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Naturinfo 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Naturinfo/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Naturinfo/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Naturinfo/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Tiltak

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Tiltak finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Tiltak/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Tiltak 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Tiltak 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Tiltak/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Tiltak 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Tiltak/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Tiltak/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Tiltak/5.0/
|2021-09-26


|===

=== FKB-TraktorvegSti

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-TraktorvegSti finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-TraktorvegSti/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-TraktorvegSti 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-TraktorvegSti 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-TraktorvegSti/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-TraktorvegSti 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-TraktorvegSti/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-TraktorvegSti/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-TraktorvegSti/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Vann

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Vann finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Vann/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Vann 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Vann 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Vann/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Vann 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Vann/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Vann/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Vann/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===

=== FKB-Veg

_Tekst om viktigste endringer og ev. problemstillinger man spesielt vil ha tilbakemelding på_

Endringslogg for FKB-Veg finner du http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Veg/5.0/#trueendringslogg[her].

.Høringsdokumenter for FKB-Veg 5.0
[cols="3*", options="header"]
|===
|Dokument
|Link
|Dato

|Standardisert produktspesifikasjon FKB-Veg 5.0 (HTML)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Veg/5.0/
|2021-09-27

|Standardisert produktspesifikasjon FKB-Veg 5.0 (PDF)
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Veg/5.0/
|2021-09-27

|GML Schema
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Veg/5.0/
|2021-09-26

|GML eksempelfil
|http://skjema.geonorge.no/SOSITEST/produktspesifikasjon/FKB-Veg/5.0/
|2021-09-26

|Fotogrammetrisk registreringsinstruks
|Foreløpig ikke klar. Legges etter planen ut ca 10.oktober
|-

|===
