= Høringsnotat: FKB 5.1
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2024-02-01


CAUTION: {publisert} 


== FKB 5.1 Høring 

Standardiseringsprosjektet for revisjon av FKB startet opp i desember 2023. Se side på geonorge for prosjektforslag og bakgrunnsnotat: https://www.geonorge.no/Geodataarbeid/standardisering/slik-jobber-vi-med-standardisering/prosjekter-og-horinger/Revisjon-av-FKB-5.0/

Målet med denne revisjonen er å gjøre en teknisk oppgradering av en del av FKB 5.0 datamodellene slik at de fungerer bedre i forvaltningssystemet for FKB (SFKB) og dataflyten inn og ut av dette. 

Når vi gjør en revisjon er det også mulig å gjøre andre mindre justering/presiseringer/forbedringer i standardene, men tidsramma for prosjektet er styrende (og kort) og det legges ikke opp til en komplett 
gjennomgang av datainnholdet i FKB i denne revisjonen. Ev. innspill til større endringer i FKB som kommer inn i prosessen må derfor med stor sannsynlighet skyves til en senere og større gjennomgang. 

=== Dokumenter på høring

Følgende standarder er på høring i denne revisjonen:
* https://htmlpreview.github.io/?https://github.com/kartverket/standard_fkb_generell_del/blob/master/generell_del/index.html[FKB-Generell del]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_ar5/blob/master/produktspesifikasjon/index.html[FKB-AR5]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygnanlegg/blob/master/produktspesifikasjon/index.html[FKB-BygnAnlegg]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygning/blob/master/produktspesifikasjon/index.html[FKB-Bygning]
* https://htmlpreview.github.io/?https://github.com/kartverket/fkb_ledning/blob/master/produktspesifikasjon/index.html[FKB-Ledning]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_tiltak/blob/master/produktspesifikasjon/index.html[FKB-Tiltak]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_traktorvegsti/blob/master/produktspesifikasjon/index.html[FKB-TraktorvegSti]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_vann/blob/master/produktspesifikasjon/index.html[FKB-Vann]
* https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_veg/blob/master/produktspesifikasjon/index.html[FKB-Veg]

Linkene i lista over viser til en visning av dokumentene direkte fra repoet i github der dokumentene utarbeides/lagres.

Se endringslogg i dokumentene for detaljert oversikt over hva som er endret. Dokumentene for FKB 5.1 er kun tilgjengelig som HTML (og ikke PDF).

==== Andre relevante ressurser i forbindelse med høringen

* Høringsversjoner av HTML-dokumentene finnes også som forslag i https://register.geonorge.no/produktspesifikasjoner[produktspesifikasjonsregisteret på Geonorge].
* GML-skjemafiler (xsd) for høringsversjonene finnes som forslag i https://register.geonorge.no/gml-applikasjonsskjema[skjemaregisteret på Geonorge].
* UML-modellene ligger med status "utkast" i SOSI-modellregister og kan sees i https://objektkatalog.geonorge.no/[objektregisteret i Geonorge].

=== Tilbakemeldinger på høringen

FKB 5.1 er først og fremst en teknisk oppgradering av FKB datamodellene som inneholder mindre tekniske tilpasninger for å få datamodellene til å fungere godt 
i forvaltningen i Sentral FKB og dataflyten inn og ut av dette systemet.

En viktig del av høringen er å teste datamodellene praktisk i Sentral FKB

Testmiljø i SFKB
NGIS-OpenAPI
Geosynkronisering-API 

