= Arbeidsdokument: FKB 5.1 revisjon
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2023-12-08


CAUTION: {publisert} 


== FKB 5.1 revisjon 

Dette dokumentet er ment som et arbeidsdokument i forbindelse med standardiseringsprosjektet for revisjon av FKB med oppstart desember 2023. 

Se side på geonorge for prosjektforslag og bakgrunnsnotat: https://www.geonorge.no/Geodataarbeid/standardisering/slik-jobber-vi-med-standardisering/prosjekter-og-horinger/Revisjon-av-FKB-5.0/

Målet med denne revisjonen er å gjøre en teknisk oppgradering av en del av FKB 5.0 datamodellene slik at de fungerer bedre i forvaltningssystemet for FKB (SFKB) og dataflyten inn og ut av dette. 

Når vi gjør en revisjon er det også mulig å gjøre andre mindre justering/presiseringer/forbedringer i standardene, men tidsramma for prosjektet er styrende (og kort) og det legges ikke opp til en komplett 
gjennomgang av datainnholdet i FKB i denne revisjonen. Ev. innspill til større endringer i FKB som kommer inn i prosessen må derfor med stor sannsynlighet skyves til en senere og større gjennomgang. 

=== Arbeidsmetode

UML-datamodellene for FKB ligger i SOSI-modellregister. De tekniske justeringene som er beskrevet i
https://www.geonorge.no/globalassets/geonorge2/standardisering/prosjekter/forslag-til-nye-prosjekter/fkb-5.1/vedlegg-endringsbehov-fkb-5.0.pdf[vedlegget til revisjonsprosjektet]
er innarbeida i nye UML-pakker med status "Utkast" i modellregisteret.

Arbeidet med å utarbeide dokumentasjon fra FKB produktspesifikasjoner og registreringsinstrukser er nå flyttet ut i åpne repoer på github.com/kartverket. 
Dette innebærer at asciidoc-filer, figurer og ferdige html-filer løpende er tilgjengelige på github. Det er utarbeida arbeidsversjoner av flere av de berørte standardene 
med eksporter fra de nye UML-modellene i modellregisteret som er tilgjengelig på github. 

=== Skisse til prosess i standardiseringsprosjektet _Revisjon av FKB_

* Utkast til UML-modeller og arbeidsdokumenter der tekniske oppgraderinger er tatt inn er utarbeida og sendes ut ved oppstart
* Det innkalles til et oppstartsmøte med følgende agenda:
** Forslag til endringer gjennomgås raskt
** Avklaringspunkter definert i vedlegg til prosjektforslag tas opp til diskusjon
** Det åpnes for innspill utover det som er beskrevet i prosjektforslaget
* Prosjektledelsen vurderer behov for ev. videre prosess på innkomne forslag
* Prosjektledelsen utarbeider høringsversjoner av dokumentene og sender på høring 
* Høringsinnspill innarbeides og endelige versjoner tilgjengeliggjøres

Det er et mål å ha endelige versjoner at FKB 5.1 tilgjengelige i løpet av februar 2024. Det innebærer at dokumentene må ut på høring i midten av januar.

== Utarbeida arbeidsdokumenter med forslag til nye FKB 5.1 datamodeller/dokumenter

Se endringslogg i dokumentene for oversikt over hva som er endret.

Alle linker i dokument metadataene etc. vil ikke nødvendigvis virke i disse arbeidsdokumentene som vises direkte fra github. Dette vil bli ryddet opp i forbindelse med utarbeidig av høringsversjoner.

=== FKB Generell del

Repo på github.com/kartverket: https://github.com/kartverket/standard_fkb_generell_del

- https://htmlpreview.github.io/?https://github.com/kartverket/standard_fkb_generell_del/blob/master/generell_del/index.html[HTML-visning av arbeidsdokument]


=== FKB-BygnAnlegg

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygnanlegg

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygnanlegg/blob/master/produktspesifikasjon/index.html[HTML-visning av arbeidsdokument]


=== FKB-Bygning 

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_bygning

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_bygning/blob/master/produktspesifikasjon/index.html[HTML-visning av dokument]


=== FKB-Ledning 

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_ledning

- https://htmlpreview.github.io/?https://github.com/kartverket/fkb_ledning/blob/master/produktspesifikasjon/index.html[HTML-visning av dokument]


=== FKB-Tiltak

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_tiltak

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_tiltak/blob/master/produktspesifikasjon/index.html[HTML-visning av dokument]


=== FKB-TraktorvegSti

Repo på github.com/kartverket: https://github.com/kartverket/prodspek_fkb_traktorvegsti

- https://htmlpreview.github.io/?https://github.com/kartverket/prodspek_fkb_traktorvegsti/blob/master/produktspesifikasjon/index.html[HTML-visning av dokument]


