== Definisjoner og forkortelser

=== Definisjoner

.digital høydemodell (DHM)  
en digital representasjon av høydeverdier som varierer over en flate

_MERKNAD_: En DHM er en samling av et stort antall høydepunkter på en flate. Punktene kan være organisert som et regelmessig rutenett eller i et mer uregelmessig mønster. Den siste metoden vil normalt gi den beste beskrivelsen av flaten. Alternativ engelsk betegnelse er ”Digital Elevation Model (DEM)”.

.digital terrengmodell (DTM)  
en DHM som beskriver terrengoverflaten uten vegetasjon, bygninger og andre objekter

.digital overflatemodell (DOM)  
en DHM som beskriver overflaten av terrenget inkludert objekter som vegetasjon, bygninger etc.

_MERKNAD_: Alternativ engelsk betegnelse er «Digital Surface Model (DSM)». 

.flybåren laserskanning  
måling av avstand mellom en lasersensor, i fly eller helikopter, og terrengoverflaten

_MERKNAD_: Flybåren laserskanning kalles også laseraltimetri.  

.Fotogrammetrisk punktsky 
Punktsky generert ved hjelp av fotogrammetriske metoder.  

_MERKNAD_ :	kalles også bildematching eller med den engelske betegnelsen «Dense image matching» 

.Multistråle ekkolodd 
Måling av avstand ved hjelp av akkustikk under vann.  

_MERKNAD_: kalles også MBES fra den engelske betegnelsen «Multi Beam Eccho Sounding» 

.Terrestrisk skanning 
Måling av avstand mellom en lasersensor plassert på «bakkenivå» og objekter rundt sensoren. 

_MERKNAD_: sensorer montert på kjøretøy, stativ eller håndholdte sensorer passer alle inn her. 

.kvalitet 
helheten av egenskaper en enhet har og som vedrører dens evne til å tilfredsstille uttalte og underforståtte behov [NS-ISO 8402 def. 2.1] 

_MERKNAD_:
I Geodatastandarden er det definert seks kvalitetselementer: 
 * stedfestingsnøyaktighet 
 * egenskapsnøyaktighet 
 * logisk konsistens (kontroll av logiske regler/sammenhenger) 
 * fullstendighet 
 * datasettets historikk og tidligere bruk 
 * tilgjengelighet og leveringstid 

.laserskanning fotavtrykk 
lasersensorens opptaksområde på overflaten

_MERKNAD_: Alternativ engelsk betegnelse er ”footprint” 

.laserskanning punkttetthet 
antall laserpulser som treffer en flate pr. m2

.teoretisk punkttetthet 
antall laserpulser (førstereturer) som treffer en flate pr. m2 i områder uten overlapp mellom stripene 
_MERKNAD_: Dette er en teoretisk verdi som beregnes ut fra flyhøyde, flyhastighet, parametere i laserskanneren etc. I praksis vil punktettheten varierer innenfor et område pga. forskjeller i terrenghøyden, dødvinkler med mer. 

.laserskanning skannevinkel 
laserstrålens vinkel i forhold til loddlinjen 

_MERKNAD_: På grunn av turbulens vil ikke instrumentets 0-retning (alltid) treffe bakken med 90 graders vinkel. 

.metadata  
informasjon som beskriver et datasett
 
_MERKNAD_: Hvilke opplysninger som inngår i metadataene, kan variere avhengig av datasettets karakter. Vanlige opplysninger er innhold, kvalitet, tilstand, struktur, format, produsent og vedlikeholdsansvar. 

.produktspesifikasjon
detaljert beskrivelse av ett datasett eller en serie med datasett med tilleggsinformasjon som gjør det mulig å produsere, distribuere og bruke datasettet av andre (tredjepart)

_MERKNAD_: En dataproduktspesifikasjon kan lages for produksjon, salg, sluttbrukervirksomhet eller annet. 

=== Forkortelser

*NDH*: Nasjonal detaljert høydemodell  

*NHM*: Nasjonal høydemodell (produktene fra prosjektet NDH) 

*DHM*: Digital høydemodell 

*DOM*: Digital overflatemodell 

*DTM*: Digital terrengmodell 

*FKB*: Felles KartdataBase 

*ALS*: Airborne Laser Scanning 

*ALB*: Airborne Lidar Bathymetry 

*LIDAR*: Light Detection And Ranging, betegner et prinsipp for avstandsmålingen 

*MBES*: Multi-Beam Echo Sounding 

*SOSI*: Samordnet Opplegg for Stedfestet Informasjon - et standardformat for digitale geodata (SOSI-standarden) 

*UML*: Unified Modelling Language. Modelleringsspråk som brukes til å beskrive geografiske  datamodeller 