=== Generelle prinsipper for registrering av høydeverdier

Det generelle prinsippet for FKB er at dataene registreres i 2.5D med krav til stedfestingsnøyaktighet i både grunnriss og høyde. Kravet til stedfestingsnøyaktighet på høydeverdiene setter krav til registreringen av den enkelte koordinat.

Utover dette kravet presiseres det i tillegg at koordinatene bør registreres i naturlige "knekklinjer" på objektene. Altså slik at geometrien fanger opp repoer i trapper, avsatser på tribuner etc. og gir en best mulig gjengivelse av objektet i 3 dimensjoner.  

==== Krav til registrering av høydesprang

Mange objekttyper i FKB kan ha høydesprang. Se f.eks. skisse og beskrivelse under objektttype Skjerm. Dette kan i mange tilfeller også omfatte avgrensningen av flateobjekter som f.eks. Bru. Dersom høydesprangene er større enn verdiene angitt i tabellen under skal det registreres høydesprang. Dvs. at geometrien til objektet registreres 2 punkter med (mer eller mindre) lik koordinat i grunnriss, men ulik høydekoordinat. 

[[tab-hoydesprang]]
.Høydesprang større enn angitt i tabellen under skal registreres i FKB
[cols="2*", options="header"]
|===

|FKB-Standard
|Høydesprang

|FKB-A / FKB-B
|0,5 m

|FKB-C / FKB-D
|1 m 

|===

