= Oppfølging av høringsinnspill
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2021-11-26


CAUTION: {publisert} 

== Overordna

Abeidet gjøres i UML-modellene, i kodelisteregisteret på Geonorge og i adoc-filene lagret i repositorie dokumentasjon_fkb på bitbucket: https://bitbucket.statkart.no/projects/PROF/repos/dokumentasjon_fkb/browse

Bitbucket tar vare på all historikk så høringsversjoner (adoc/html/pdf) kan bare overskrives. PDF-varianter av høringsversjonene er lagret unna på \\statkart.no\Fellesdata\SKFelles\Geovekst\Standarder og spesifikasjoner\Produktspesifikasjon for FKB\Versjon50-2022 som en lett tilgjengelig ekstra backup.

== Følges opp av prosjektledelsen sentralt 
Prosjektledelsen sentralt = Nils med bistand

* Alle endringer i UML-modell for generelle konsepter
* Alle endringer i dokumentet FKB generell del
* Alle endringer i fellesdelene i adoc (som inkluderes i de enkelte dokumentene)
* Generere ut maskinlesbar dokumentasjon fra oppdaterte UML-modeller:
** GML-Schema 
** Schematron-filer
** SOSI-kontroll filer
* Generere PDF-dokumentasjon fra ferdig oppdaterte adoc-filer


== Følges opp av standardiseringssekretariatet

* Oppdatere OCL-syntaks for restriksjoner i UML-modellene (utført!)
* Oppdatere skript for eksport av dokumentasjon fra UML til adoc (utført!)
* Sjekke samsvar i SOSI tagged values mellom datatyper og egenskaper som benytter datatyper i UML-modellene (vha. skript!?) 
* Sjekke samsvar i SOSI tagged values mellom kodelister og egenskaper som benytter kodelister i UML-modellene (vha. skript!?) 
* Oppdatere skript for eksport av SOSI-realisering fra UML til adoc (behov avklares!)
* Oppdatere skript for eksport fra registreringsintruks til adoc (behov avklares!)
* Samle sammen og tilgjengeliggjøre kommentarskjemaer
* Sende ut ferdig dokumentasjon til godkjenning i SKG
* Tilgjengeliggjøre ferdig dokumentasjon når godkjent (?)
* Mer/annet?


== Følges opp av den enkelte arbeidsgruppe
Den enkelt arbeidsgruppe = prosjektleder + ansvarlig for UML-modellering og dokumentasjon.

*Endringer i UML-modell:*

* Gjøre reelle justeringer i UML datamodellen som følge av høringsinnspillene (i tråd med omforent behandling i arbeidsgruppa og høringskommentar)
* Sørge for at tagger på pakkenivå er i tråd med innspill fra standardiseringssekretariatet:
** SOSI_spesifikasjonstype skal ha verdien _produktspesifikasjon_
** SOSI_kortnavn skal angis uten skilletegn og versjonsnummer. Eks. _FKBBygning_
** xsdDocument skal være identisk med SOSI_kortnavn ".xsd". Eks. _FKBBygning.xsd_
** Avsluttende "/" fjernes på targetNamespace og ev. andre tagger der verdien angis som en url
** Fjerne "utkast" som del av pakkenavn og endre statuskode for pakka
* Hente inn oppdateringer fra UML-modellen "Generelle elementer". 
** Endringene er i OCL + innføring av sluttdato. Antagelig raskest å gjøre denne jobben i hvert datasett framfor å kopiere inn pakke og tilpasse/koble opp på nytt.
* Gå gjennom alle diagrammer og vurdere raskt om de kan/bør forbedres i tråd med "best practice": https://github.com/ISO-TC211/UML-Best-Practices/wiki/Best-practices-for-diagram-design
** Om visning av tagger i UML-diagrammer: Bør unngås på featuretyper og datatyper, men kan brukes på kodelister for å vise fram url til ekstern kodeliste.


*Endringer i Geonorge kodelisteregister:*

* Gå gjennom kodelistene på Geonorge. Gi alle kodelister og kodelisteverdier status "Gyldig", _Gyldig fra_ dato til "2022-01-01"og vurder om kodeverdiene kan/bør forkortes/forenkles
** Skal være "kortest mulig" og som hovedregel undert 10 tegn (jf. beskrivelse i nytt punkt i FKB-generell del). Særlig der vi innfører nye kodelister/kodeverdier bør vi ta en sjekk på at verdiene er nogenlunde i tråd med beskrivelsen.


*Endringer på bitbucket (adoc-filer + ev. skisser):*

* Endre dokument-tittel fra "SOSI standardisert produktspesifikasjon" til SOSI-standardisert produktspesifikasjon"
* Kap 1.1: Legg til følgende setninger avslutningsvis: «Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.» 
* Kap 1.3: Oppdater med ev. justeringer som følge av høringsinnspill 
* Kap 3.1.1: Kortnavn skal være lik "SOSI_kortnavn" i UML-modellen, men med skilletegn. Eks. _FKB-Bygning_
* Kap 3.4: Skal ha verdien "nor" (og ikke "Norsk")
* Kap 3.5: Dette er et fritekstfelt. Vurdere om det kan legges til mer konkrete "temakategorier" i tillegg til basisdata. Eks. _Bygning_ for FKB-Bygning.
* Kap 3.6: Hentes fra en kodeliste. Skal ha verdien "basisData".
* Kap 3.8: Vurdere om det kan legges inn litt tekst som beskriver formålet til FKB-datasettet i tillegg til den generelle teksten som beskriver formålet til FKB (som inkluderes som en felles-del)
* Endre til :toclevels: 4 i hodet på adoc-fila (??)
* Legge til alternativ bildetekst på alle bilder/skisser som legges inn i adoc (image::bilde-url[Alt="Tekst som beskriver bildet"])
* Generere ut ny Adoc-dokumentasjon fra UML-modellen. 
* Generere ut ny SOSI-realisering fra UML-modellen
* Generere ny HTML-dokumentasjon og se over ("korrekturlese") at helheten i dokumentet er ok.

== Avklaringspunkter

??
