= Oppfølging av høringsinnspill
:sectnums:
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:figure-caption: Figur
:table-caption: Tabell
:doctype: article
:encoding: utf-8
:lang: nb
:publisert: Oppdatert 2021-11-26


CAUTION: {publisert} 


== Overordna

=== Avklaringspunkter

* Standardisere navn på geometriegenskaper til posisjon, grense/senterlinje og område?
* Standardisere verdi på geometriegenskaper til GM_point, GM_Curve og GM_Surface (i stedet for punkt, kurve, flate)?

== Følges opp av prosjektledelsen sentralt 
Prosjektledelsen sentralt = Nils med bistand

* Alle endringer i UML-modell for generelle konsepter
* Alle endringer i dokumentet FKB generell del
* Alle endringer i fellesdelene i adoc (som inkluderes i de enkelte dokumentene)

== Følges opp av standardiseringssekretariatet

* Oppdatere OCL-syntaks for restriksjoner i UML-modellene (utført!)
* Oppdatere skript for eksport av dokumentasjon fra UML til adoc (utført!)
* Sjekke samsvar i SOSI tagged values mellom datatyper og egenskaper som benytter datatyper i UML-modellene (vha. skript!?) 
* Sjekke samsvar i SOSI tagged values mellom kodelister og egenskaper som benytter kodelister i UML-modellene (vha. skript!?) 
* Oppdatere skript for eksport av SOSI-realisering fra UML til adoc (behov avklares!)
* Oppdatere skript for eksport fra registreringsintruks til adov (behov avklares!)
* ??


== Følges opp av den enkelte arbeidsgruppe
Den enkelt arbeidsgruppe = prosjektleder + ansvarlig for UML-modellering og dokumentasjon

* Hente inn oppdateringer fra UML-modelle "Generelle elementer" (kopiere inn og koble opp på nytt??)
* Gå gjennom alle diagrammer  