= Huskeliste UML-modellering av Fotogrammetrisk registreringsinstruks: FKB-Ledning 5.0

:fkbdatasett: FKB-Ledning 5.0

== Tilpassing av "ApplicationSchema"
Når man tar en kopi av "ApplicationSchema" pakka for produktspesifikasjonen {fkbdatasett} må følgende tilpasninger gjøres i kopien som legges under repository "Fotogrammetrisk {fkbdatasett}"

* Egenskapen _identifikasjon_ endres fra [1..1] til [0..1]
* Egenskapen _oppdateringsdato_ endres fra [1..1] til [0..1]
* Legg inn en *constraint* på klassen "KvalitetPåkrevd"
** Verbal tekst: "Hvis Registreringsversjon FKB 5.0 2022-01-01 skal Posisjonskvalitet angis med Nøyaktighet og NøyaktighetHøyde"
** OCL: "inv: self.registreringsversjon = 2022-01-01 implies ((self.nøyaktighet->Size() = 1 and self.nøyaktighetHøyde->Size() = 1) or (self.nøyaktighet->Size() = 1))"
* Legg inn en *constraint* på klassen "Fellesegenskaper"
** Verbal tekst: "Hvis Identifikasjon ikke er angitt skal Registreringsversjon FKB 5.0 2022-01-01 angis"
** OCL: "inv: self.identifikasjon->Size() = 0 implies self.registreringsversjon = 2022-01-01"
* Fjern (slett) featuretypene Jordingsledning og Luftlinje
** Fjern (slett) kodelisten Fase tilhørende Luftlinje
