
=== Referansesystemer for forvaltning av FKB

FKB-data er detaljerte data med høy presisjon. Dette betyr at man må være bevisst på mulige feil som kan innføres ved transformasjon av dataene mellom forskjellige romlige referansesystemer. 
All forvaltning av FKB-data baserer seg på den norske realiseringen av referanserammene EUREF89 (ETRS89-NOR) i grunnriss og NN2000 med oppdatert høydereferansemodell i høyde.

I forvaltningen av FKB-data gjøres vanligvis oppdateringen direkte i den aktuelle kommunens koordinatsystem slik at man unngår transformasjon av data. 
Kommuner i Finnmark fylke har UTM35 som lokal sone. Kommuner i Nordland og Troms har UTM33 som lokal sone, mens kommuner fra Trøndelag og sørover bruker UTM32 som lokal sone. 

Dersom det skal tillates oppdatering med transformasjon inn i FKB-dataene må det benyttes en transformasjon som gir presisjon bedre enn oppløsningen i FKB-dataene (i praksis bedre en ca 5 mm).

**Endringer i referanserammer i 2027:**

I løpet av 2027 gjøres 2 endringer som har med referanserammer å gjøre:

* Det innføres nye EPSG-koder som presiserer at EUREF89 i norsk sammenheng henviser til ETRS89-NOR i stedet for den generelle europeiske referanserramma. Dette er altså ikke en endring av referanseramma for dataene, men bare en endring i metadataene. Dataene endres ikke, men metadataene endres slik at de spesifiserer hvilken referanseramme som er brukt mer presist.

* Høydereferansemodellen oppdateres. Dette er en reell endring i referanserammen og medfører behov for omregning av koordinatverdier i enkelte områder. Tidligere har høydedatum kun blitt angitt som NN2000. Heretter innføres hvilken høydereferansemodell som er benyttet som et tillegg i betegnelsen. Tidligere NN2000 betegnes heretter som NN2000:2018 og NN2000:2025 brukes som ny betegnelse på data som forholder seg til NN2000 med høydereferansemodell fra 2025. 

Alle systemer som håndterer FKB-data må håndtere både nye og gamle referansesystemer. Se tabeller under for oversikt over endringer.

.Liste over romlige referansesystem som benyttes i forvaltningen av FKB-data i 2026
[cols="3*", options="header"]
|===
|Referansesystem
|SOSI-kode
|EPSG-kode

|ETRS89-NOR [EUREF89] / UTM zone 32N
|Koordsys 22, Vert-datum ikke angitt
|25832 (kode for europeisk EUREF89)

|ETRS89-NOR [EUREF89] / UTM zone 33N
|Koordsys 23, Vert-datum ikke angitt
|25833 (kode for europeisk EUREF89)

|ETRS89-NOR [EUREF89] / UTM zone 35N
|Koordsys 25, Vert-datum ikke angitt
|25835 (kode for europeisk EUREF89)

|ETRS89-NOR [EUREF89] / UTM zone 32N + NN2000
|Koordsys 22, Vert-datum NN2000
|5972

|ETRS89-NOR [EUREF89] / UTM zone 33N + NN2000
|Koordsys 23, Vert-datum NN2000
|5973

|ETRS89-NOR [EUREF89] / UTM zone 35N + NN2000
|Koordsys 25, Vert-datum NN2000
|5975
|===


.Liste over romlige referansesystem som benyttes i forvaltningen av FKB-data etter overgang i 2027
[cols="3*", options="header"]
|===
|Referansesystem
|SOSI-kode
|EPSG-kode

|ETRS89-NOR [EUREF89] / UTM zone 32N
|Koordsys 22, Vert-datum ikke angitt
|11022

|ETRS89-NOR [EUREF89] / UTM zone 33N
|Koordsys 23, Vert-datum ikke angitt
|11023

|ETRS89-NOR [EUREF89] / UTM zone 35N 
|Koordsys 25, Vert-datum ikke angitt
|11025

|ETRS89-NOR [EUREF89] / UTM zone 32N + NN2000:2018 
|Koordsys 22, Vert-datum NN2000:2018
|5972

|ETRS89-NOR [EUREF89] / UTM zone 33N + NN2000:2018 
|Koordsys 23, Vert-datum NN2000:2018
|5973

|ETRS89-NOR [EUREF89] / UTM zone 35N + NN2000:2018 
|Koordsys 25, Vert-datum NN2000:2018
|5975

|ETRS89-NOR [EUREF89] / UTM zone 32N + NN2000:2025 
|Koordsys 22, Vert-datum NN2000:2025
|11403

|ETRS89-NOR [EUREF89] / UTM zone 33N + NN2000:2025 
|Koordsys 23, Vert-datum NN2000:2025
|11404

|ETRS89-NOR [EUREF89] / UTM zone 35N + NN2000:2025 
|Koordsys 25, Vert-datum NN2000:2025
|11406
|===

=== Referansesystemer for distribusjon og bruk av FKB-data

Kommunevise data distribueres i lokal UTM-sone. For landsdekkende data distribueres data i UTM33. Referanserammen vil alltid identifiseres presist av metadataene (EPSG- eller SOSI-kode) og det er viktig at denne informasjonen benyttes korrekt av klientsystemene som håndterer dataene.  

FKB-data inngår i mange typer distribusjoner/tjenester. I mange sammenhenger vil det være behov for å transformere FKB-dataene til andre koordinatsystemer for bruk sammen med andre datakilder.  
Det kan oppstå unøyaktigheter i disse transformasjonene så om man ønsker full nøyaktighet på dataene så anbefales det å forholde seg til referanserammene som brukes i forvaltningen. Om man har behov for å transfomere data så må man ha et bevisst forhold til hvilke transformasjoner som gjøres og med hvilke verktøy disse transformasjonene gjøres. 
 
